### PR TITLE
Make it easier for visitors of Docker HUB to find this repository

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by Tekki** [comment]
Thanks. I'll have to add this change to the template too so it's not overriden at the next update.

**Comment by szabgab** [comment]
Interesting, so the readme was generated from a template? Where is the template? I could not find it.

**Comment by Tekki** [comment]
Yes, it's at `templates/readme.ep`.

**Comment by szabgab** [comment]
:+1:

**Pull request merged**
